# SPDX-FileCopyrightText: 2025 Rena and 小光
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = "**"
precedence = "closest"
SPDX-FileCopyrightText = "2025 Rena and 小光"
SPDX-License-Identifier = "CC0-1.0"
