# SPDX-FileCopyrightText: 2025 Rena and LCG
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = "item_hover.mp3"
precedence = "aggregate"
copyright = "ZapSplat"
SPDX-FileCopyrightText = "ZapSplat <https://www.zapsplat.com>"
SPDX-License-Identifier = "LicenseRef-ZapSplat-Standard"

[[annotations]]
path = "item_select.mp3"
precedence = "aggregate"
copyright = "ZapSplat"
SPDX-FileCopyrightText = "ZapSplat <https://www.zapsplat.com>"
SPDX-License-Identifier = "LicenseRef-ZapSplat-Standard"

[[annotations]]
path = "menu_close.mp3"
precedence = "aggregate"
copyright = "ZapSplat"
SPDX-FileCopyrightText = "ZapSplat <https://www.zapsplat.com>"
SPDX-License-Identifier = "LicenseRef-ZapSplat-Standard"

[[annotations]]
path = "menu_open.mp3"
precedence = "aggregate"
copyright = "ZapSplat"
SPDX-FileCopyrightText = "ZapSplat <https://www.zapsplat.com>"
SPDX-License-Identifier = "LicenseRef-ZapSplat-Standard"

[[annotations]]
path = "parent_hover.mp3"
precedence = "aggregate"
copyright = "ZapSplat"
SPDX-FileCopyrightText = "ZapSplat <https://www.zapsplat.com>"
SPDX-License-Identifier = "LicenseRef-ZapSplat-Standard"

[[annotations]]
path = "parent_select.mp3"
precedence = "aggregate"
copyright = "ZapSplat"
SPDX-FileCopyrightText = "ZapSplat <https://www.zapsplat.com>"
SPDX-License-Identifier = "LicenseRef-ZapSplat-Standard"

[[annotations]]
path = "submenu_hover.mp3"
precedence = "aggregate"
copyright = "ZapSplat"
SPDX-FileCopyrightText = "ZapSplat <https://www.zapsplat.com>"
SPDX-License-Identifier = "LicenseRef-ZapSplat-Standard"

[[annotations]]
path = "submenu_open.mp3"
precedence = "aggregate"
copyright = "ZapSplat"
SPDX-FileCopyrightText = "ZapSplat <https://www.zapsplat.com>"
SPDX-License-Identifier = "LicenseRef-ZapSplat-Standard"
